### ISSUE TITLE
Outdated Documentation Links

### ISSUE THREAD

**Issue by Mongwell** [pyne/pyne#1142]
Hi, my name's Maanu Grover. I'm a CS undergrad in Professor Katy Huff's research group for the summer. After going through the PyNE README and documentation, I found a few links that could be updated, namely: the Anaconda download links no longer work, and the PyNE releases linked to use for installation are rather old releases.

Opening this issue to link a PR to it.

**Comment by nathanb01** [comment]
I found another broken link in the documentation. In [`theorymanual/data.rst`](https://github.com/pyne/pyne/blob/develop/docs/theorymanual/data.rst), the `ORIGEN-S data`  link doesn't work. I attempted to track down the document that it was meant to link to but was unsuccessful.

**Comment by nsryan2** [comment]
Website Links:

* [ ] In the open ORIGEN Data example note book, there’s a link http://web.ornl.gov/info/reports/1980/3445605762840.pdf that doesn’t work
* CCCC Formats in the user’s guide had several broken links (these all return “Service Unavailable”)
   * [x] http://t2.lanl.gov/codes/transx-hyper/isotxs.html (#1311)
   * [x] http://t2.lanl.gov/codes/transx-hyper/matxs.html (#1311)
   * [x] http://t2.lanl.gov/codes/transx-hyper/rtflux.html (#1311)
   * [x] http://t2.lanl.gov/codes/transx-hyper/rzflux.html (#1311)
* [x] ACE Cross Sections also has http://t2.lanl.gov/codes.shtml which produces  “Service Unavailable” (#1311)
* [x] JsonCpp: Python bindings for … Json Cpp has moved here https://github.com/open-source-parsers/jsoncpp  (#1311)
* [x] Rigorous Two-Step Activation (R2S) Alara User’s Guide link doesn’t work "ALARA Input and Output Interfaces” http://alara.engr.wisc.edu/users.guide.html/  (#1311)
* Reaction names page
    * [x] the link source http://t2.lanl.gov/endf/mts.html for http://pyne.io/pyapi/rxname.html#id3 doesn’t work. It leads to a lanl site that says "return “Service Unavailable.” (#1311)
    * [ ] http://wwwndc.jaea.go.jp/form/ENDF6/mt.html which is the source link for http://pyne.io/pyapi/rxname.html#id4 also doesn’t work
* [ ] pyne.xs.data_source.RX_TYPES pyne.xs.data_source.RX_TYPES_MAP ﻿ ﻿are both supposed to be links in the nuclear reaction channels page which is linked in the cross section interface page at the bottom and it appears
* These pages have no links to the sources of any of their functions or classes:
    * [ ] http://pyne.io/pyapi/enrichment.html
    * [ ] http://pyne.io/pyapi/bins.html
    * [ ] http://pyne.io/pyapi/cram.html
    * [ ] http://pyne.io/pyapi/ace.html
    * [ ] http://pyne.io/pyapi/endf.html
    * [ ] http://pyne.io/pyapi/ensdf.html
    * [ ] http://pyne.io/pyapi/stlcontainers.html
    * [ ] http://pyne.io/pyapi/jsoncpp.html
* [ ] On Endf File Support page http://www-nds.iaea.org/ndspub/documents/endf/endf102/endf102.pdf doesn’t work  
* No contact link on PyNE development team for:
    * [ ] Cameron Bates
    * [ ] NIck Touran
    * [x] Paul Wilson (#1311)
* [x] The link to ENSDF manual (https://www.nndc.bnl.gov/nndcscr/documents/ensdf/ensdf-manual.pdf) is broken on http://pyne.io/theorymanual/data.html (#1311)
* [x] The link to ORIGEN-S data (http://web.ornl.gov/~webworks/cppr/y2001/rpt/97914.pdf) is broken on http://pyne.io/theorymanual/data.html (#1311)
* [x] The JSONCPP linked (http://jsoncpp.sourceforge.net/) has moved here (https://github.com/open-source-parsers/jsoncpp) on http://pyne.io/previous/0.2_release_notes.html (#1311)
* [ ] Building the PyNE website cloud sphinx theme has moved to https://cloud-sptheme.readthedocs.io/en/latest/cloud_theme.html
* [ ] Style Guide C++ Style Guide link is broken and doesn’t lead anywhere
* [ ] Style guide - Python style guide - the link that says described here has been moved to https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard 
* [ ] The google C++ Style guide (here http://pyne.io/devsguide/style_guide.html#c-c-style-guide) is broken
* [ ] The GCSG link (here http://pyne.io/devsguide/style_guide.html#namespaces) is broken
