### ISSUE TITLE
Todo at the end of the release: 

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1313]
- [ ] Update Tar Zip link on Webster (install section) #1278
- [ ] Update VM to the latest develop (use release tag)
- [ ] Publish a new version of the website
- [ ] check install scripts

---------------
fill free to edit and add items to the list
